# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_auto_20160811_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dollhouse',
            name='user',
        ),
    ]
